name: build

on:
  push:
    branches:
      - 'v*.*.*'
      - '*.*.*'
      - 'main'
              
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

  
      - name: Extract Version Number
        id: extract_version_number
        run: echo "##[set-output name=version;]$(echo $GITHUB_REF |cut -d '/' -f 3 | cut -c 2- )"
        
      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/samplescript
          echo -e "echo sample" > .debpkg/usr/bin/samplescript
          chmod +x .debpkg/usr/bin/samplescript
          echo -e "a=1" > .debpkg/usr/lib/samplescript/samplescript.conf

      - name: upload custom certificates
        run: |
          mkdir -p .debpkg/usr/share/ca-certificates
          cp -r certs/* .debpkg/usr/share/ca-certificates

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
      - uses: jiro4989/build-deb-action@v3
        with:
          package: samplescript
          package_root: .debpkg
          maintainer: your_name
          version: 1.0.0
          arch: 'amd64'
          depends: 'libc6 (>= 2.2.1), git'
          desc: 'this is sample package.'
      - name: setup git config
        run: |
          git config user.name shaposhnikoff
          git config user.email max@shaposhnikoff.info
          git add *.deb
          git commit -m "latest"
          git push origin main
          
