name: build

on:
  push:
    branches:
      - 'v*.*.*'
      - '*.*.*'
      
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name of debian package.'
        required: true
      package_root:
        description: 'Directory of release files.'
        required: true
      maintainer:
        description: 'Package maintainer name.'
        required: true
      Version:
        description: 'Package version.'
        required: true
      installed_size:
        description: 'Package installed size. GitHub Actions set summarized byte size of `package_root` directory when this parameter is empty.'
        default: ''
        required: false
      depends:
        description: 'Package dependencies.'
        default: 'none'
        required: false
      arch:
        description: 'Package architecture.'
        default: 'amd64'
        required: false
      desc:
        description: 'Package description.'
        default: ''
        required: false
      compress_type:
        description: >
          Set the compression type used when building.
          Allowed types gzip, xz, zstd, none.
          Default is gzip.
        default: 'gzip'
        required: false

        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract Version Number
        id: extract_version_number
        run: echo "##[set-output name=version;]$(echo $GITHUB_REF |cut -d '/' -f 3 | cut -c 2- )"
        
      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/samplescript
          echo -e "echo sample" > .debpkg/usr/bin/samplescript
          chmod +x .debpkg/usr/bin/samplescript
          echo -e "a=1" > .debpkg/usr/lib/samplescript/samplescript.conf

          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst
      - uses: jiro4989/build-deb-action@v3
        with:
          package: samplescript
          package_root: .debpkg
          maintainer: your_name
          version: ${{ steps.extract_version_number.outputs.version }}
          arch: 'amd64'
          depends: 'libc6 (>= 2.2.1), git'
          desc: 'this is sample package.'
      - name: setup git config
        run: |
          git config user.name shaposhnikoff
          git config user.email max@shaposhnikoff.info
          git add .
